# -*- coding: utf-8 -*-
"""Crop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1terB3cWNeZbEHnG9bcfFjvshzOc9etDS
"""

import pandas as pd

df = pd.read_csv("/content/Crop_recommendation.csv")
print(df.head())
print(df.tail())

df.columns

df.shape

unique_crops = df['label'].unique()
print(unique_crops)
print(unique_crops.shape)

df['label'].unique()

df.info()

mean_values = df.mean(numeric_only=True)
print("Mean values:\n", mean_values)
print('==============================')
median_values = df.median(numeric_only=True)
print("Median values:\n", median_values)
print('==============================')
max_values = df.max(numeric_only=True)
print("Max values:\n", max_values)
print('==============================')
min_values = df.min(numeric_only=True)
print("Min values:\n", min_values)
print('==============================')
std_values = df.std(numeric_only=True)
print("Std values:\n", std_values)

print(df.isnull().sum())
print('==================')
print(df.duplicated().sum())

df.describe(include='number')

df.describe(include='object')

import pandas as pd

df = pd.read_csv("/content/Crop_recommendation.csv")
print(df.dtypes)
print('===================================')
crop_counts = df['label'].value_counts()
print(crop_counts)

df = df.drop_duplicates()
print(df.isnull().sum())

X = df.drop('label', axis=1)
y = df['label']

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y)

print(le.classes_)

print(y_encoded)

for i, crop in enumerate(le.classes_):
    print(i, "->", crop)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000
)

model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

y_pred = model.predict(X_test_scaled)

from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))



cm = confusion_matrix(y_test, y_pred)
print(cm)

import pickle

with open("crop_model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

with open("label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)